### PR TITLE
ZEP-2107: Add phone to Contacts endpoint parameters and responses

### PR DESCRIPTION
**Pull request by zachingle**
[ZEP-2107](https://zeptoau.atlassian.net/browse/ZEP-2107)

Add a phone number field to the following endpoint request parameters:
- Add a Contact `POST /contacts/anyone`
- Update a Contact `PATCH /contacts/{id}`

Update the responses for the following endpoints:
- Add a Contact `POST /contacts/anyone`
- List all Contacts `GET /contacts`
- Get a Contact `GET /contacts/{id}`
- Update a Contact `PATCH /contacts/{id}`

### Add a Contact
Before
image
image

After
Screen Shot 2022-06-14 at 8 44 17 am
image

### List all Contacts 
Before
image

After
image

### Get a Contact
Before
image

After
image

### Update a Contact
Before
image
image

After
image
image

### CODE REVIEW

**Review by SmileAndCompile — APPROVED** [review]
LGTM! Nitpick - I think some before / after screenshots are always helpful

**Comment by corroded** [comment]
> LGTM! Nitpick - I think some before / after screenshots are always helpful

💯 yes please! 🙏

**Comment by zachingle** [comment]
Screenshots added

**Review by corroded — APPROVED** [review]
Nice work! 💯

**Pull request merged**
