### PR TITLE
ZEP-1757: update uri to nz

### PR DESCRIPTION
**Pull request by dylan-zepto**
## 💡 Why
* [ZEP-1757](https://zeptoau.atlassian.net/browse/ZEP-1757)

## 📝 What

* Updated AU links to NZ equivalent as per Jira card description

* Also deleted PR template message as no longer relevant (current NZ repo was not forked from slate repo)

### CODE REVIEW

**Review by markbiegel — APPROVED** [review]
👌

**Review by friendlyantz — APPROVED** [review]
in order to connect your ticket with Jira, use the following naming convention in future:
`ZEP-1757: name_of_your_pr`

also consider using `markdown` syntax / bullet points / etc. there are some quick tutorials online

**Review by corroded — APPROVED** [review]
giphy (1)

**Comment by dylan-zepto** [comment]
Thanks @friendlyantz will follow this convention moving forward

**Pull request merged**
